### ISSUE TITLE
Gemini.get_response fails for tilde.pink

### ISSUE THREAD

**Issue by soapingtime** [milouse/ruby-net-text#1]
Reproduction: `./bin/heraut 'gemini://tilde.pink'`

Error: 

```
$ ./bin/heraut 'gemini://tilde.pink'

/home/soap/ruby-net-text/lib/net/gemini/response/parser.rb:14:in `block in received_mime': undefined method `downcase' for nil (NoMethodError)

          key = opt[0].downcase.to_sym
                      ^^^^^^^^^
        from /home/soap/ruby-net-text/lib/net/gemini/response/parser.rb:13:in `each'
        from /home/soap/ruby-net-text/lib/net/gemini/response/parser.rb:13:in `filter_map'
        from /home/soap/ruby-net-text/lib/net/gemini/response/parser.rb:13:in `received_mime'
        from /home/soap/ruby-net-text/lib/net/gemini/response/parser.rb:30:in `parse_meta'
        from /home/soap/ruby-net-text/lib/net/gemini/response.rb:45:in `initialize'
        from /home/soap/ruby-net-text/lib/net/gemini/response.rb:97:in `new'
        from /home/soap/ruby-net-text/lib/net/gemini/response.rb:97:in `read_new'
        from /home/soap/ruby-net-text/lib/net/gemini/client.rb:25:in `request!'
        from /home/soap/ruby-net-text/lib/net/gemini/client.rb:31:in `request'
        from /home/soap/ruby-net-text/lib/net/gemini/client.rb:47:in `fetch'
        from /home/soap/ruby-net-text/lib/net/gemini/client.rb:88:in `block in get_response'
        from /home/soap/ruby-net-text/lib/net/gemini/client.rb:84:in `start'
        from /home/soap/ruby-net-text/lib/net/gemini/client.rb:88:in `get_response'
        from ./bin/heraut:17:in `<main>'
```

**Comment by milouse** [comment]
Thank you very much for your report. I just pushed a fixed for this issue and release a new version of the gem.
